### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by OL1Y1ER** [BenjaminPV/DomotiX#9]
- [ ] Wifi test with Arduino (exp turning on an LED)
- [ ] Making the architecture for communication between devices
- [ ] testing if data is shown, being sent
- [ ] Illustrating the data
- [ ] making it do something when there is a problem
- [ ] adding cool stuff (camera + NeuralNetwork?, alarm system in case of break-in?, security system with passw?)
